// @ts-check

import {
  assertEnvironment,
  moduleExport
} from '@-xun/symbiote/assets/eslint.config.mjs';

import { createDebugLogger } from 'rejoinder';

const debug = createDebugLogger({ namespace: 'symbiote:config:eslint' });

const config = await moduleExport({
  derivedAliases: getEslintAliases(),
  ...(await assertEnvironment())
});

config.push({
  /* Add custom config here, such as disabling certain rules */
});

export default config;

debug('exported config: %O', config);

function getEslintAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return [
    ['multiverse+checks:*', './packages/checks/src/*'],
    ['multiverse+extensions:*', './packages/extensions/src/*'],
    ['multiverse+checks', './packages/checks/src/index.ts'],
    ['multiverse+extensions', './packages/extensions/src/index.ts'],
    ['rootverse+checks:*', './packages/checks/*'],
    ['rootverse+extensions:*', './packages/extensions/*'],
    ['rootverse:*', './*'],
    ['universe+checks:*', './packages/checks/src/*'],
    ['universe+extensions:*', './packages/extensions/src/*'],
    ['universe+checks', './packages/checks/src/index.ts'],
    ['universe+extensions', './packages/extensions/src/index.ts'],
    ['universe:*', './src/*'],
    ['universe', './src/index.ts'],
    ['testverse+checks:*', './packages/checks/test/*'],
    ['testverse+extensions:*', './packages/extensions/test/*'],
    ['testverse:*', './test/*'],
    ['typeverse:*', './types/*']
  ];
}
