// @ts-check
'use strict';

import { deepMergeConfig } from '@-xun/symbiote/assets';
import { assertEnvironment, moduleExport } from '@-xun/symbiote/assets/jest.config.mjs';
import { createDebugLogger } from 'rejoinder';

const debug = createDebugLogger({ namespace: 'symbiote:config:jest' });

const config = deepMergeConfig(
  moduleExport({ derivedAliases: getJestAliases(), ...assertEnvironment() }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
    transformIgnorePatterns: ['/node_modules/', '/test/fixtures/']
  }
);

export default config;

debug('exported config: %O', config);

function getJestAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^multiverse\\+checks:(.+)$': '<rootDir>/packages/checks/src/$1',
    '^multiverse\\+extensions:(.+)$': '<rootDir>/packages/extensions/src/$1',
    '^multiverse\\+checks$': '<rootDir>/packages/checks/src/index.ts',
    '^multiverse\\+extensions$': '<rootDir>/packages/extensions/src/index.ts',
    '^rootverse\\+checks:(.+)$': '<rootDir>/packages/checks/$1',
    '^rootverse\\+extensions:(.+)$': '<rootDir>/packages/extensions/$1',
    '^rootverse:(.+)$': '<rootDir>/$1',
    '^universe\\+checks:(.+)$': '<rootDir>/packages/checks/src/$1',
    '^universe\\+extensions:(.+)$': '<rootDir>/packages/extensions/src/$1',
    '^universe\\+checks$': '<rootDir>/packages/checks/src/index.ts',
    '^universe\\+extensions$': '<rootDir>/packages/extensions/src/index.ts',
    '^universe:(.+)$': '<rootDir>/src/$1',
    '^universe$': '<rootDir>/src/index.ts',
    '^testverse\\+checks:(.+)$': '<rootDir>/packages/checks/test/$1',
    '^testverse\\+extensions:(.+)$': '<rootDir>/packages/extensions/test/$1',
    '^testverse:(.+)$': '<rootDir>/test/$1',
    '^typeverse:(.+)$': '<rootDir>/types/$1'
  };
}
